version: '3.5'

services:
  database:
    image: mariadb/server:10.3
    restart: always
    volumes:
      - vol.database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - net

  website:
    depends_on:
      - database
    image: wordpress:latest
    restart: always
    volumes:
      - vol.website:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  vol.database:
  vol.website:
